spring:
  application:
    name: meedog-search
  profiles:
    active: dev #默认为开发环境

server:
  port: 9083

mybatis:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:com/**/mapper/*.xml



