spring:
  datasource:
    url: jdbc:mysql://"xxxxxx":3306/meedog_db_test?useUnicode=true&characterEncoding=utf-8&nullCatalogMeansCurrent=true&serverTimezone=Asia/Shanghai
    username: xxxxxx
    password: "XXXXXX"
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: xxxxxx
        login-password: xxxxxx
  data:
    elasticsearch:
      repositories:
        enabled: true
    redis:
      repositories:
        enabled: false
  elasticsearch:
    rest:
      uris: "xxxxxx":9200
      max-search-results: 200
      max-per-search-results: 20

logging:
  file:
    path: ./logs
  level:
    root: info
    com.macro.meedog: info
    org.springframework.data.convert.CustomConversions: ERROR
