server:
  port: 9085

spring:
  http:
    multipart.location = /var/tmp

  datasource:
    url: jdbc:mysql://"xxxxxx":3306/meedog_db?useUnicode=true&characterEncoding=utf-8&nullCatalogMeansCurrent=true&serverTimezone=Asia/Shanghai
    username: xxxxxx
    password: "XXXXXX"
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: xxxxxx
        login-password: xxxxxx

  data:
    mongodb:
      host: "xxxxxx"
      port: 27017
      database: meedog-server

  redis:
    host: "xxxxxx" # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password:  "XXXXXX" # Redis服务器连接密码（默认为空）
    timeout: 300ms # 连接超时时间（毫秒）
  kafka:
    bootstrap-servers: "xxxxxx":9092
    admin:
      connections-max-idle-ms: 540000
      metadata-max-age-ms: 300000
      client-id: meedog-admin

    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      group-id: 'meedog-test'
      enable-auto-commit: true
      auto-commit-interval-ms: 5000
      session-timeout-ms: 30000
      fetch-min-bytes: 1
      max-partition-fetch-bytes: 1048576

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      buffer-memory: 33554432
      batch-size: 16384
      linger-ms: 1000
      retries: 0
    listener:
      log-container-config: false
      concurrency: 5
  mail:
    default-encoding: UTF-8
    host: smtp.163.com
    username: "xxxxxx"
    password:
    port: 25
    protocol: smtp
    test-connection: false
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.ssl.enable: true

logging:
  file:
    path: /deploy/meedog/logs
  level:
    root: info
    com.macro.meedog: info

wx:
  getCode: "https://open.weixin.qq.com/connect/oauth2/authorize?appid=%s&redirect_uri=%s&response_type=code&scope=%s&state=STAT#wechat_redirect"
  webAccessTokenhttps: "https://api.weixin.qq.com/sns/jscode2session?appid=%s&secret=%s&js_code=%s&grant_type=authorization_code"
  appId: xxxxxx
  secret: xxxxxx


